// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dnorm_rank1
double dnorm_rank1(const NumericVector& x, const NumericVector& v, const NumericVector& s_diag, const NumericVector& mu, bool return_log);
RcppExport SEXP UltimateDeconvolution_dnorm_rank1(SEXP xSEXP, SEXP vSEXP, SEXP s_diagSEXP, SEXP muSEXP, SEXP return_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type s_diag(s_diagSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< bool >::type return_log(return_logSEXP);
    rcpp_result_gen = Rcpp::wrap(dnorm_rank1(x, v, s_diag, mu, return_log));
    return rcpp_result_gen;
END_RCPP
}
// get_llike_mat_cpp
NumericMatrix get_llike_mat_cpp(const NumericMatrix& x_mat, const NumericMatrix& s_mat, const NumericMatrix& v_mat, const NumericVector& pi_vec);
RcppExport SEXP UltimateDeconvolution_get_llike_mat_cpp(SEXP x_matSEXP, SEXP s_matSEXP, SEXP v_matSEXP, SEXP pi_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type s_mat(s_matSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_mat(v_matSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi_vec(pi_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(get_llike_mat_cpp(x_mat, s_mat, v_mat, pi_vec));
    return rcpp_result_gen;
END_RCPP
}
// dmixlike_cpp
double dmixlike_cpp(const NumericMatrix& x_mat, const NumericMatrix& s_mat, const NumericMatrix& v_mat, const NumericVector& pi_vec, bool return_log);
RcppExport SEXP UltimateDeconvolution_dmixlike_cpp(SEXP x_matSEXP, SEXP s_matSEXP, SEXP v_matSEXP, SEXP pi_vecSEXP, SEXP return_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type s_mat(s_matSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_mat(v_matSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi_vec(pi_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type return_log(return_logSEXP);
    rcpp_result_gen = Rcpp::wrap(dmixlike_cpp(x_mat, s_mat, v_mat, pi_vec, return_log));
    return rcpp_result_gen;
END_RCPP
}
// em_fix_cpp
void em_fix_cpp(const NumericMatrix& x_mat, const NumericMatrix& s_mat, NumericMatrix& v_mat, NumericVector& pi_vec);
RcppExport SEXP UltimateDeconvolution_em_fix_cpp(SEXP x_matSEXP, SEXP s_matSEXP, SEXP v_matSEXP, SEXP pi_vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type s_mat(s_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type v_mat(v_matSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type pi_vec(pi_vecSEXP);
    em_fix_cpp(x_mat, s_mat, v_mat, pi_vec);
    return R_NilValue;
END_RCPP
}
// em_cpp
List em_cpp(const NumericMatrix& x_mat, const NumericMatrix& s_mat, NumericMatrix& v_mat, NumericVector& pi_vec, int itermax, double tol, bool plot_iter);
RcppExport SEXP UltimateDeconvolution_em_cpp(SEXP x_matSEXP, SEXP s_matSEXP, SEXP v_matSEXP, SEXP pi_vecSEXP, SEXP itermaxSEXP, SEXP tolSEXP, SEXP plot_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type s_mat(s_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type v_mat(v_matSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type pi_vec(pi_vecSEXP);
    Rcpp::traits::input_parameter< int >::type itermax(itermaxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type plot_iter(plot_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(em_cpp(x_mat, s_mat, v_mat, pi_vec, itermax, tol, plot_iter));
    return rcpp_result_gen;
END_RCPP
}
