// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dnorm_rank1
double dnorm_rank1(NumericVector x, NumericVector v, NumericVector s_diag, NumericVector mu, bool return_log);
RcppExport SEXP UltimateDeconvolution_dnorm_rank1(SEXP xSEXP, SEXP vSEXP, SEXP s_diagSEXP, SEXP muSEXP, SEXP return_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s_diag(s_diagSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< bool >::type return_log(return_logSEXP);
    rcpp_result_gen = Rcpp::wrap(dnorm_rank1(x, v, s_diag, mu, return_log));
    return rcpp_result_gen;
END_RCPP
}
