# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multivariate normal density at mean 0 and a covariance that is the sum
#' of a rank-1 matrix and a diagonal matrix.
#'
#' @inheritParams dr1_norm
#' @param return_log Should we return the log-density (\code{TRUE}) or not (\code{FALSE})?
#'
#' @author David Gerard
#'
#' @export
#'
dnorm_rank1 <- function(x, v, s_diag, mu, return_log = FALSE) {
    .Call('UltimateDeconvolution_dnorm_rank1', PACKAGE = 'UltimateDeconvolution', x, v, s_diag, mu, return_log)
}

