# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multivariate normal density at mean 0 and a covariance that is the sum
#' of a rank-1 matrix and a diagonal matrix.
#'
#' @inheritParams dr1_norm
#' @param return_log Should we return the log-density (\code{TRUE}) or not (\code{FALSE})?
#'
#' @author David Gerard
#'
#' @export
#'
dnorm_rank1 <- function(x, v, s_diag, mu, return_log = FALSE) {
    .Call('UltimateDeconvolution_dnorm_rank1', PACKAGE = 'UltimateDeconvolution', x, v, s_diag, mu, return_log)
}

#' Get's a matrix of likeklihood values.
#'
#' Element (i, j) of the returned matrix is the log of
#' pi_j N(x_i | 0, v_j v_j^T + S_i)
#'
#' @inheritParams dmixlike
#'
#' @author David Gerard
#'
get_llike_mat_cpp <- function(x_mat, s_mat, v_mat, pi_vec) {
    .Call('UltimateDeconvolution_get_llike_mat_cpp', PACKAGE = 'UltimateDeconvolution', x_mat, s_mat, v_mat, pi_vec)
}

#' Calculates the gaussian mixture density.
#'
#' This function assumes that the mixing means are all zeros and
#' the mixing covariances are rank-1 matrices. Each observation
#' has its own independent noise (variances collected in
#' \code{s_mat}).
#'
#' @inheritParams dmixlike
#' @param return_log A logical. Should we return the log-density
#'     (\code{TRUE}) or not (\code{FALSE})?
#'
#' @author David Gerard
#'
dmixlike_cpp <- function(x_mat, s_mat, v_mat, pi_vec, return_log = FALSE) {
    .Call('UltimateDeconvolution_dmixlike_cpp', PACKAGE = 'UltimateDeconvolution', x_mat, s_mat, v_mat, pi_vec, return_log)
}

#' Fixed point iteration from the EM algorithm.
#'
#' @inheritParams dmixlike
#'
#' @author David Gerard
#'
em_fix_cpp <- function(x_mat, s_mat, v_mat, pi_vec) {
    .Call('UltimateDeconvolution_em_fix_cpp', PACKAGE = 'UltimateDeconvolution', x_mat, s_mat, v_mat, pi_vec)
}

